set nocompatible                    " be iMproved
set ttimeoutlen=50
" set noesckeys
set showcmd                         " Show me what I'm doing
set ic                              " Ignore case when searching with "/"

" C++11 syntax workaround
let c_no_curly_error=1
syntax enable

set number
set relativenumber
set ruler
set noautoindent
set nosmartindent
set hidden
set backspace=indent,eol,start
set hls
set t_ut=

command Vrc edit ~/.vimrc

" Do not clear clipboard on exit
autocmd VimLeave * call system("xsel -ib", getreg('+'))
" Delete trailing whitespace
autocmd FileType c,cpp,proto,rl call SetCodeOptions()
function SetCodeOptions()
    " autocmd BufWritePre <buffer> %s/\s\+$//e
    set nowrap
endfunction

command StripTrailingWhitespace %s/\s\+$//e

highlight ExtraWhitespace ctermbg=darkgreen
autocmd ColorScheme * highlight ExtraWhitespace ctermbg=darkgreen
match ExtraWhitespace /\s\+$/

set exrc
set secure

set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set scrolloff=8
set scroll=4
autocmd BufWinEnter * silent! set scroll=4

let &path.="src/include,/usr/include/c++/5,/usr/include/x86_64-linux-gnu/c++/5"

autocmd BufRead,BufNewFile /usr/include/c++/*,/usr/include/x86_64-linux-gnu/c++/*,/usr/include/linux/* call SetLibStdCppOptions()
function SetLibStdCppOptions()
    set ft=cpp
    set tabstop=8
endfunction

let g:ycm_global_ycm_extra_conf = '/home/olan/.vim/bundle/YouCompleteMe/third_party/ycmd/examples/.ycm_extra_conf.py'
let g:AutoPairsShortcutToggle = '<C-p>'
let g:AutoPairsShortcutJump = '<C-n>'
let g:AutoPairsShortcutFastWrap = '<C-e>'
let g:AutoPairsMultilineClose = 0
let g:AutoPairsMapCR = 0

" Vundle stuff
filetype off
set rtp+=~/.vim/bundle/Vundle.vim/
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'

" General
Plugin 'henrik/vim-indexed-search'          " Show how many matches were found when searching with '/'
Plugin 'jiangmiao/auto-pairs'               " Pair quotes, brackets, etc.
Plugin 'vim-scripts/BufOnly.vim'
Plugin 'tomtom/enabler_vim'

" C/C++ stuff
" Plugin 'vim-scripts/Cpp11-Syntax-Support'   " Proper C++11 syntax highlighting
" Plugin 'Valloric/YouCompleteMe'
" Plugin 'mom0tomo/dotfiles'
" Plugin 'wincent/command-t'
" Plugin 'vim-scripts/Conque-GDB'
" Plugin 'vim-scripts/git-time-lapse'
" Plugin 'vim-scripts/a.vim'                  " Quick switching betwean .h/.cpp
" " Plugin 'jeaye/color_coded'

" Color schemes
Plugin 'endel/vim-github-colorscheme'
" Plugin 'ajh17/Spacegray.vim'
" Plugin 'tomasiser/vim-code-dark'
" Plugin 'AlessandroYorba/Arcadia.git'
" Plugin 'bruth/vim-newsprint-theme'
" Plugin 'AlessandroYorba/Despacio'
" Plugin 'mtglsk/wikipedia.vim'

call vundle#end()
filetype plugin indent on

function CppEnable()
    Enable Cpp11-Syntax-Support   " Proper C++11 syntax highlighting
    Enable YouCompleteMe
    Enable dotfiles
    Enable command-t
    Enable Conque-GDB
    Enable git-time-lapse
    Enable a.vim                  " Quick switching betwean .h/.cpp
endfunction
command CppEnable :call CppEnable()

colorscheme github

" nnoremap <C-S-r> gd[{V%::s/<C-R>///gc<left><left><left>
nnoremap <F2> :YcmCompleter GoTo <CR>
nnoremap <F5> :highlight ExtraWhitespace ctermbg=darkgreen <CR>
nnoremap <S-F5> :highlight ExtraWhitespace NONE <CR>
nnoremap <F6> :%s/\s\+$//e <CR>
nnoremap <F12> :vsplit +vertical\ resize\ 35\|e. <CR>
nnoremap <S-F12> :close 1 <CR> :set scroll=4 <CR>
let g:netrw_chgwin=2
map <F4> :silent! A <CR>
map <F3> :set relativenumber! <CR>
nnoremap <C-k> :CommandT <CR>

nnoremap  y  "+y
nnoremap  yy "+yy
nnoremap  Y  "+Y
nnoremap  p  "+p
nnoremap  P  "+P
vnoremap y  "+y
vnoremap D  "+d
vnoremap y  "+y
vnoremap p  "+p
vnoremap P  "+P
vnoremap <C-_> c/*<C-R>"*/<Esc>
nmap ,cs :let @+=expand("%")<CR>
nmap ,cl :let @+=expand("%:p")<CR>

" let g:ycm_autoclose_preview_window_after_insertion = 1
let g:ycm_confirm_extra_conf = 0

" set efm=
" set efm+=%*[^\"]\"%f\"%*\\D%l:\ %m
" set efm+=,\"%f\"%*\\D%l:\ %m
" set efm+=,%-G%f:%l:\ (Each\ undeclared\ identifier\ is\ reported\ only\ once
" set efm+=,%-G%f:%l:\ for\ each\ function\ it\ appears\ in.)
" 
" " To disable tagging of these lines, change '+' to '-'
" set efm+=,%+GIn\ file\ included\ from\ %f:%l:%c:
" set efm+=,%+GIn\ file\ included\ from\ %f:%l:%c\\,
" set efm+=,%+GIn\ file\ included\ from\ %f:%l:%c
" set efm+=,%+GIn\ file\ included\ from\ %f:%l
" set efm+=,%+Gfrom\ %f:%l:%c
" set efm+=,%+Gfrom\ %f:%l:
" set efm+=,%+Gfrom\ %f:%l\\,
" set efm+=,%+Gfrom\ %f:%l
" 
" set efm+=,%f:%l:%c:%m
" set efm+=,%f(%l):%m
" set efm+=,%f:%l:%m
" set efm+=,\"%f\"\\,\ line\ %l%*\\D%c%*[^\ ]\ %m
" set efm+=,%D%*\\a[%*\\d]:\ Entering\ directory\ %*[`]%f
" set efm+=,%X%*\\a[%*\\d]:\ Leaving\ directory\ %*[`]%f
" set efm+=,%D%*\\a:\ Entering\ directory\ %*[`]%f
" set efm+=,%X%*\\a:\ Leaving\ directory\ %*[`]%f
" set efm+=,%DMaking\ %*\\a\ in\ %f
