set nocompatible                    " be iMproved
set showcmd                         " Show me what I'm doing
set ic                              " Ignore case when searching with "/"
syntax enable
set number
set relativenumber
set ruler
set noautoindent
set nosmartindent
set hidden
set backspace=indent,eol,start

command Vrc edit ~/.vimrc

" Do not clear clipboard on exit
autocmd VimLeave * call system("xsel -ib", getreg('+'))
" Delete trailing whitespace
autocmd FileType c,cpp,proto,rl call SetCodeOptions()
function SetCodeOptions()
    autocmd BufWritePre <buffer> %s/\s\+$//e
    set nowrap
endfunction

highlight ExtraWhitespace ctermbg=darkgreen
autocmd ColorScheme * highlight ExtraWhitespace ctermbg=darkgreen
match ExtraWhitespace /\s\+$/

set exrc
set secure

set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set scrolloff=8
set scroll=4
autocmd BufWinEnter * silent! set scroll=4

let &path.="src/include,/usr/include/c++/5,/usr/include/x86_64-linux-gnu/c++/5"

autocmd BufRead,BufNewFile /usr/include/c++/*,/usr/include/x86_64-linux-gnu/c++/*,/usr/include/linux/* call SetLibStdCppOptions()
function SetLibStdCppOptions()
    set ft=cpp
    set tabstop=8
endfunction

let g:ycm_global_ycm_extra_conf = '/home/olan/.vim/bundle/YouCompleteMe/third_party/ycmd/examples/.ycm_extra_conf.py'
let g:AutoPairsShortcutToggle = '<C-p>'
let g:AutoPairsShortcutJump = '<C-n>'
let g:AutoPairsShortcutFastWrap = '<C-e>'
let g:AutoPairsMultilineClose = 0
let g:AutoPairsMapCR = 0

" Vundle stuff
filetype off
set rtp+=~/.vim/bundle/Vundle.vim/
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'Valloric/YouCompleteMe'
" Plugin 'jeaye/color_coded'
Plugin 'jiangmiao/auto-pairs'
Plugin 'ajh17/Spacegray.vim'
Plugin 'mom0tomo/dotfiles'
Plugin 'wincent/command-t'
Plugin 'henrik/vim-indexed-search'
Plugin 'vim-scripts/Conque-GDB'
Plugin 'vim-scripts/a.vim'
Plugin 'vim-scripts/BufOnly.vim'
Plugin 'tomasiser/vim-code-dark'
Plugin 'AlessandroYorba/Arcadia.git'
Plugin 'bruth/vim-newsprint-theme'
Plugin 'AlessandroYorba/Despacio'
Plugin 'mtglsk/wikipedia.vim'
Plugin 'endel/vim-github-colorscheme'

call vundle#end()
filetype plugin indent on

colorscheme github

" nnoremap <C-S-r> gd[{V%::s/<C-R>///gc<left><left><left>
nnoremap <F2> :YcmCompleter GoTo <CR>
nnoremap <F5> :YcmCompleter GoToImprecise <CR>
nnoremap <F12> :vsplit +vertical\ resize\ 35\|e. <CR>
nnoremap <S-F12> :close 1 <CR> :set scroll=4 <CR>
let g:netrw_chgwin=2
map <F4> :silent! A <CR>
map <F3> :set relativenumber! <CR>
nnoremap <C-k> :CommandT <CR>
noremap  y  "+y
noremap  yd "+d
noremap  yy "+yy
noremap  Y  "+Y
noremap  p  "+p
noremap  P  "+P
vnoremap y  "+y
vnoremap yd "+d
vnoremap yy "+yy
vnoremap Y  "+Y
vnoremap p  "+p
vnoremap P  "+P

" let g:ycm_autoclose_preview_window_after_insertion = 1
let g:ycm_confirm_extra_conf = 0
