#!/bin/bash

as -o /tmp/olan.a.out <<<"$@"                                          \
&& objdump -s --disassemble /tmp/olan.a.out                            \
| tail -1                                                              \
| python -c 'import sys; print sys.stdin.read().split(":")[1].strip()'
