#!/bin/bash

TMPFILE=`mktemp --tmpdir cw-XXXXXX`
unbuffer "$@" |& tee >(ansifilter >${TMPFILE})
CMD_EXIT_STATUS=${PIPESTATUS[0]}
printf "\\e]51;[\"call\", \"Tapi_FillQuickfixWindow\", \"${TMPFILE}\"]\\x07"
exit ${CMD_EXIT_STATUS}
