#!/bin/bash

for arg; do
    case "${arg}" in
        -v)
            VERBOSE='1'
            ;;
        *)
            if [ -z "${BRANCH}" ]; then
                BRANCH="${arg}"
            else
                COMPONENTS[${#COMPONENTS}]="${arg}"
            fi
            ;;
    esac
done

error() {
    echo "${1}" 1>&2
    exit 1
}

PROJECTS_DIR='/home/olan/git/drweb'
ENV_DIR='/home/olan/job'

if [ -z "${BRANCH}" ]; then
    link=`readlink "${PROJECTS_DIR}/drweb-unix-configd"`
    if [ ! $? -eq 0 ]; then
        echo 'Cannot figure out branch of drweb-unix-configd: realink failed' 1>&2
        exit 1
    fi
    echo "${link}" | cut -d '-' -f 4
    exit 0
fi

relink() {
    target="${1}-${BRANCH}"
    link="${1}"

    if [ ! -e "${target}" ]; then
       [ -n "${VERBOSE}" ] && echo "No such file or directory: ${target}"
       return 0
    fi

    mv -f "${link}" "${link}-backup"
    if ln -f -s "${target}" "${link}"; then
        rm -f "${link}-backup"
    else
        mv -f "${link}-backup" "${link}"
    fi
    [ -n "${VERBOSE}" ] && echo "${link} -> ${target}"
}

if [ ${#COMPONENTS} -gt 1 ]; then
    shift
    for component in "${COMPONENTS[@]}"; do
        relink "drweb-unix-${component}"
    done
else
    find -P "$PROJECTS_DIR" -maxdepth 1 -type l | while read file; do
        echo "${file}" | grep -q backup || relink "$file"
    done
    for i in "${ENV_DIR}/dw-user-env"[0123456789] "${HOME}/bin/"{cfd,ctl}[0123456789]; do
        relink "$i"
    done
fi

exit 0
